spring:
  application:
    name: inflearn-springboot-jpa-1

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jpa-learn;
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      data-locations: classpath:schema.sql
      mode: always
      platform: h2

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
